# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-13 20:27
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False, verbose_name='User ID')),
                ('c_name', models.CharField(max_length=30, verbose_name='User Name')),
                ('c_email', models.EmailField(max_length=254, verbose_name='User E-mail')),
                ('c_address', ckeditor.fields.RichTextField(verbose_name='User Address')),
                ('c_phone', models.CharField(max_length=20, verbose_name='User Phone')),
                ('c_password', models.CharField(max_length=6, verbose_name='User Password')),
                ('role', models.CharField(choices=[('Customer', 'Customer'), ('Company', 'Company')], default='Customer', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'c_name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Department ID')),
                ('d_name', models.CharField(max_length=30, verbose_name='Department Name')),
                ('d_capacity', models.IntegerField(verbose_name='Department Capacity')),
                ('d_phone', models.IntegerField(verbose_name='Department Phone')),
                ('d_password', models.CharField(max_length=6, verbose_name='Department Password')),
                ('d_slug', models.SlugField(editable=False, max_length=130, unique=True)),
                ('dCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Company', verbose_name='Company Name')),
            ],
            options={
                'ordering': ['dCompany'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Employee ID')),
                ('e_name', models.CharField(max_length=30, verbose_name='Name')),
                ('e_surname', models.CharField(max_length=30, verbose_name='Surname')),
                ('e_password', models.CharField(max_length=6, verbose_name='Password')),
                ('e_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('e_phone', models.IntegerField(verbose_name='Phone')),
                ('e_degree', models.IntegerField(verbose_name='Degree')),
                ('e_salary', models.IntegerField(verbose_name='Salary')),
                ('role', models.CharField(choices=[('Head', 'head'), ('Other', 'other')], default='Other', max_length=30)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('e_slug', models.SlugField(editable=False, max_length=130, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('eCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Company', verbose_name='Company Name')),
                ('eDepartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Department', verbose_name='Department Name')),
            ],
            options={
                'ordering': ['eCompany', 'eDepartment', '-e_degree'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('i_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Issue ID')),
                ('i_type', models.CharField(max_length=30, verbose_name='Issue Type')),
                ('i_extra', ckeditor.fields.RichTextField(verbose_name='Issue Notes')),
                ('i_content', ckeditor.fields.RichTextField(verbose_name='Issue Content')),
                ('cIssue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Company', verbose_name='Company Name')),
                ('i_work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='i_work', to='userprofile.Employee', verbose_name='Assign Employee 1')),
                ('i_work2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='i_work2', to='userprofile.Employee', verbose_name='Assign Employee 2')),
            ],
            options={
                'ordering': ['i_id', 'pIssue'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Plan ID')),
                ('plan_type', models.CharField(max_length=30, verbose_name='Plan Type')),
                ('plan_date', models.DateTimeField(verbose_name='Plan Date')),
                ('headMakes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Employee', verbose_name='Employee ID')),
            ],
            options={
                'ordering': ['plan_id', 'plan_type'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Project ID')),
                ('p_startdate', models.DateTimeField(verbose_name='Project Start Date')),
                ('p_enddate', models.DateTimeField(verbose_name='Project End Date')),
                ('p_title', models.CharField(max_length=75, verbose_name='Project Title')),
                ('p_situation', models.CharField(max_length=20, verbose_name='Project Situation')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('p_slug', models.SlugField(editable=False, max_length=130, unique=True)),
                ('cProject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Company', verbose_name='Company Name')),
                ('dProject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Department', verbose_name='Department Name')),
                ('eProject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eProject', to='userprofile.Employee', verbose_name='Project Manager')),
                ('sProject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sProject', to='userprofile.Employee')),
            ],
            options={
                'ordering': ['p_enddate'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_type', models.CharField(max_length=30, verbose_name='Report Type')),
                ('r_version', models.CharField(max_length=5, verbose_name='Report Version')),
                ('r_createdate', models.DateTimeField(verbose_name='Report Create Date')),
                ('oReport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Employee', verbose_name='Prepare Employee ID')),
                ('pReport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Project', verbose_name='Project ID')),
            ],
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Subtask ID')),
                ('sub_content', ckeditor.fields.RichTextField(verbose_name='Subtask Content')),
                ('iIssue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Issue', verbose_name='Issue ID')),
                ('sCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Company', verbose_name='Company Name')),
                ('s_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Employee', verbose_name='Assign Employee')),
            ],
            options={
                'ordering': ['sub_id', 'iIssue'],
            },
        ),
        migrations.CreateModel(
            name='WorkFlow',
            fields=[
                ('w_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Workflow ID')),
                ('w_type', models.CharField(max_length=30, verbose_name='Workflow Type')),
                ('w_date', models.DateTimeField(verbose_name='Workflow Date')),
                ('w_content', ckeditor.fields.RichTextField(verbose_name='Workflow')),
            ],
            options={
                'ordering': ['w_id', 'w_type'],
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='pPlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Project', verbose_name='Project ID'),
        ),
        migrations.AddField(
            model_name='issue',
            name='pIssue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.Project', verbose_name='Project Name'),
        ),
    ]
